spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hrm?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.126.com
    username: wxdonger@126.com
    password: qwert12345
    port: 25
    protocol: smtp
    default-encoding: utf-8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis:
  type-aliases-package: me.wangxiaodong.hrm.module.*.dao



